name: cicd

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source1
        uses: actions/checkout@v3
      - name: Login to Docker Hub1
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ankit974/smile .
      - name: Publish image to Docker Hub
        run: docker push ankit974/smile:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: sudo docker pull ankit974/smile:latest
      #- name: Check if Container Exists
        #run: |
          #if docker ps -a --format '{{.Names}}' | grep -q '^reactContainer$'; then
          #  docker rm -f reactContainer
         # fi
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8000 --name reactContainer2 ankit974/smile:latest
